# Generated by Django 5.2.14 on 2026-07-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans_payments", "0005_payment_plans_payme_status_9ad17d_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for confirmation"),
                    ("preauth", "Pre-authorized"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("refunded", "Refunded"),
                    ("error", "Error"),
                    ("input", "Input"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
    ]
