# Generated by Django 5.2.18 on 2026-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans_payments", "0006_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="new_renew_token",
            field=models.JSONField(
                blank=True,
                help_text="Renew token received by a payment that replaces it, stored on confirmation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="replace_renew_token",
            field=models.BooleanField(
                default=False,
                help_text="Collect new payment details instead of the stored renew token; replace it once confirmed.",
                null=True,
            ),
        ),
    ]
