# Generated by Django 5.2.9 on 2025-12-11 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Intentionally NOT using swappable_dependency to replicate BlenderKit scenario
        # where migrations don't declare the dependency on the swappable model
        # Depend on plans_payments.0005 so this runs BEFORE 0006 (which creates RecurringUserPlan)
        ("plans_payments", "0005_payment_plans_payme_status_9ad17d_idx_and_more"),
        ("contenttypes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "recurring_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.PLANS_RECURRINGUSERPLAN_MODEL,
                    ),
                ),
            ],
        ),
    ]
